USE [master]
GO

/****** Object:  Database [netFoodDb]    Script Date: 07.12.2020 0:10:26 ******/
CREATE DATABASE [netFoodDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'netFoodDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\netFoodDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'netFoodDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\netFoodDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [netFoodDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [netFoodDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [netFoodDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [netFoodDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [netFoodDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [netFoodDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [netFoodDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [netFoodDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [netFoodDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [netFoodDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [netFoodDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [netFoodDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [netFoodDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [netFoodDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [netFoodDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [netFoodDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [netFoodDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [netFoodDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [netFoodDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [netFoodDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [netFoodDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [netFoodDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [netFoodDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [netFoodDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [netFoodDb] SET  MULTI_USER 
GO

ALTER DATABASE [netFoodDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [netFoodDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [netFoodDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [netFoodDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [netFoodDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [netFoodDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [netFoodDb] SET  READ_WRITE 
GO


